GET http://localhost:4000/json-utils/api/v1/health

###

POST http://localhost:4000/json-utils/api/v1/json2yml/indent/2
Content-Type: application/json

{
	"id": "0002",
	"type": "donut",
	"name": "Cake",
	"ppu": 0.55,
	"batters":
		{
			"batter":
				[
					{ "id": "1001", "type": "Regular" },
					{ "id": "1002", "type": "Chocolate" },
					{ "id": "1003", "type": "Blueberry" },
					{ "id": "1004", "type": "Devil's Food" }
				]
		},
	"topping":
		[
			{ "id": "5001", "type": "None" },
			{ "id": "5002", "type": "Glazed" },
			{ "id": "5005", "type": "Sugar" },
			{ "id": "5007", "type": "Powdered Sugar" },
			{ "id": "5006", "type": "Chocolate with Sprinkles" },
			{ "id": "5003", "type": "Chocolate" },
			{ "id": "5004", "type": "Maple" }
		]
}

###

POST http://localhost:4000/json-utils/api/v1/yml2json/indent/8
Content-Type: text/plain

id: "0001"
type: donut
name: Cake
ppu: 0.55
batters:
  batter:
    - id: "1001"
      type: Regular
    - id: "1002"
      type: Chocolate
    - id: "1003"
      type: Blueberry
    - id: "1004"
      type: Devil's Food
topping:
  - id: "5001"
    type: None
  - id: "5002"
    type: Glazed
  - id: "5005"
    type: Sugar
  - id: "5007"
    type: Powdered Sugar
  - id: "5006"
    type: Chocolate with Sprinkles
  - id: "5003"
    type: Chocolate
  - id: "5004"
    type: Maple


###

POST http://localhost:4000/json-utils/api/v1/xml2json/indent/2
Content-Type: application/xml

<xs:complexType name="fullpersoninfo">
  <xs:complexContent>
    <xs:extension base="personinfo">
      <xs:sequence>
        <xs:element name="address" type="xs:string"/>
        <xs:element name="city" type="xs:string"/>
        <xs:element name="country" type="xs:string"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>